### ISSUE TITLE
[1.0.0] Roadmap

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml#149]
This issue is for discussion and organization of the things we're working on in order to get to a stable release. Once we have a general consensus, we will close this issue, break out each of the tasks to a separate issue, and assign them to a milestone.

#### Error Reporting

Right now, error reporting capabilities are very poor, since the AST doesn't contain any information about the original file that the code came from, or about the line/column that introduced the error. Adding a filename and line/col numbers to the AST would make this much easier.

#### Source Maps

In the same vein, having the filename, line, and columns in the AST would make it possible for sourcemaps to be generated. Honestly, I am not personally interested in source maps at all, but a lot of people seem to be, and so this will be a valuable feature.

#### Code Generator > Function

Frequently it is important to be able to compile an html template into a javascript function. This approach allows the function to be used multiple times without multiple full parser runs, and enables it to be used as a client-side template, which is an important requirement given the many front-end MVC frameworks out there that use this functionality.

Currently, the only output option is an html string. I think the best route forward is to create a new code generator that outputs a stringified javascript function. For those wanting a string, a method could be implemented in posthtml to evaluate the function to get a string. Typically, these methods are named `compile` (to output a function) and `render` (to output a string).

This change would mean the introduction of a number of new types of AST nodes, as well as the ability for plugins to add "runtime functions". These are functions that must be available when the function is ultimately called, at "runtime" rather than when it is compiled ("compile time"). For example, the posthtml expressions plugin runs an html-escaping function for all normal variables, so that the user has control over what is an actual html tag vs text that contains angle brackets. It's not possible for the html-escaping function to run at compile time, since the local variables are not yet present, so the function must be made available at runtime once the user executes the function and passes in the locals. Jade/pug has a [good example of how this works](https://github.com/pugjs/pug-runtime).

The code generator (also called stringifier) should also be swappable much like the parser currently is. This way, it would be possible for people to format the output to target other formats if they wanted to.

#### Dependency Tracking

Many modern build systems track dependencies so that builds can be optimized via dependency trees. Adding an API to posthtml that would allow plugins to add dependencies would be a great benefit, allowing for only changed files to be recompiled in development for build systems implementing dependency tracking.

#### Plugin API Changes

If we add all of this stuff, there will be a number of changes to the way that plugins work. The changes will be super breaking, for sure. Plugins will gain the capability to add filenames to `dependencies`, to add data to the `runtime` (maybe this should just be the full response object, and they can add to any property they want actually), and to utilize a number of new types of AST nodes. Just speculating here entirely, and this will be up for change once things are entirely implemented, but my ideas:

- `tag`: normal html tag, needs a tag name, attributes, content. both attributes and content need to be spec-compliant ASTs
- `string`: normal string
- `expression`: javascript code, to be evaluated when the function is called

I think the three of these would cover any situation, the output function is just a string mixed with js expressions. But surely more will be learned once this is in process of being implemented.

---

So overall, here's the type of interface we're looking at, just a speculation again:

```js
const ph = posthtml({
  plugins: [...],
  parser: someParser, // optional
  stringifier: someStringifier, // optional
})

// Plugins can choose to accept options passed to compile, in addition to
// options that were passed to the plugins. This example is something like
// a partial application of local variables.
ph.compile(source, {
  sourcemap: 'external',
  filename: 'example_file.html',
  locals: { foo: 'bar' } // example
}).then((res) => {
  res.output // the function - call and it will return a string of html
  res.dependencies // array of dependencies, absolute paths
  res.sourceMap // source map, optional
  res.runtime // object containing runtime functions, if any
})
```

**Comment by zxqfox** [comment]
> Error Reporting
> Adding a filename and line/col numbers to the AST would make this much easier.

Feels like it can be reached with custom parser, right?

> The changes will be super breaking

It's totally fine since it worth. ;-)

> Source Maps
> In the same vein, having the filename, line, and columns in the AST would make it possible for sourcemaps to be generated.

Can you give some examples how you think it should looks like?

> Frequently it is important to be able to compile an html template into a javascript function.

Well, it's great. I don't get how you can compile data into a function so can you give an example?
Let's say we have a html like: `<div><a href="#anchor" title="go to anchor">click me</a></div>`. What kind of function we should get after compilation?

> expression: javascript code, to be evaluated when the function is called

Guess, `toString` (`{ tag: 'div', content: { toString: () => { return '123'; } }`) is what you looking for.



Just my 5 cents 😸

**Comment by jescalan** [comment]
> Feels like it can be reached with custom parser, right?

If htmlparser2 doesn't provide line/col numbers, then yeah a new parser would be necessary. The sugarml custom parser provides line/col numbers already if that makes any difference.

> Can you give some examples how you think it should looks like?

https://github.com/mozilla/source-map#generating-a-source-map

> Well, it's great. I don't get how you can compile data into a function so can you give an example?

```js
function template (locals) {
  return '<div><a href="#anchor" title="go to anchor">click me</a></div>'
}
```

> Guess, toString ({ tag: 'div', content: { toString: () => { return '123'; } }) is what you looking for.

Not exactly. Example of when you'd need an expression in the template:

```html
<p>{{ someLocal }}</p>
```

This compiles to a function:

```js
function template (locals) {
  return "<p>" + locals.someLocal + "</p>"
}
```

Now when you call the function:

```js
template({ someLocal: 'foo' }) // => "<p>foo</p>"
```

So the AST needs an "expression" type node for that `{{ someFunction }}` piece.

**Comment by zxqfox** [comment]
> function template (locals) {
>   return '<div><a href="#anchor" title="go to anchor">click me</a></div>'
> }

What's the point of this?

> <p>{{ someLocal }}</p>

It's posthtml, not pug or ejs, right?
In posthtml you'll have `{ tag: 'p', content: '{{ someLocal }}' }` object. You are free to mutate this object to whatever you need for your purposes, right?

>> Can you give some examples how you think it should looks like?

> https://github.com/mozilla/source-map#generating-a-source-map

Well, I hope you just don't understand me because of my english.
I mean, how you see it should works for html according to posthtml with plugins?

E.g. we have html: `<para title="title">text</para>`, plugin that modifies tag para into a section with p: `<section><h2>title</h2><p>text</p></section>` and what you expect to see as sourcemap? I don't get what you proposing, sorry.

**Comment by jescalan** [comment]
> What's the point of this?

There isn't really one, it's mostly for when you need a template, like the example below.

> It's posthtml, not pug or ejs, right?

Posthtml is a project that generates html. So is pug and ejs. Much of the time, people want to be able to generate html into a template. This entire proposal revolves around posthtml being able to generate templates. If you are working on any sort of app that has dynamic data (which is a very common use case), you will need to use a template, and static html is of little use to you. We have a plugin that [allows for some templating functionality](https://github.com/posthtml/posthtml-exp), and surely there will be more like this in the future.

> I mean, how you see it should works for html according to posthtml with plugins?

The posthtml AST would be modified to include line/column information. This information could be used to generate source maps. The plugins can modify the AST, but this doesn't change where the content came from in the original template, so source maps would still work fine unless a plugin modified the line/col data.

The sourcemap for the example you gave you point the `section` tag to the `para` tag in the original document, so that it was clear where the `section` came from. They become more useful as the transformations get more complex. For example, if you are using [sugarml](https://github.com/posthtml/sugarml) it would point resulting html tags back to a spot in your original document.

**Comment by zxqfox** [comment]
> This entire proposal revolves around posthtml being able to generate templates.

Yeah, but if you have html→html transformation it's not the same as data→html (like in pug/ejs).
It's impossible to generate compile function for html but it's possible for plugin chains (guess with browserify or something). But in the last case it does not need sourcemaps or lines since it works with structures and not templates.

> There isn't really one, it's mostly for when you need a template, like the example below.

Okay. Guess you should take a quick look at bem-xjst project that can generate html from "bemjson" format. If you accept BEM then you'll also get class names generation otherwise you can just use it for components: http://bem.github.io/bem-xjst. It uses your templates instead of plugins (posthtml approach) and compiles it in a function that awaits bemjson structure (very similar to used in posthtml).

> The posthtml AST would be modified to include line/column information.

Agree, we should do it somehow someday. What about line/column info (let's call it meta?) for attributes?

> This information could be used to generate source maps.

It's quietly hard because in that way we would store a lot more information about tokens in source code comparing to the current way.

> The plugins can modify the AST, but this doesn't change where the content came from in the original template, so source maps would still work fine unless a plugin modified the line/col data.

What if some plugin replaces or removes the node?
What about attributes?
I think sourcemaps works very good for sugaring but in our case plugins will rebuild html-structure too much. Maybe I wrong?

**Comment by zxqfox** [comment]
@jescalan Despite the discussion, are you willing to build a PoC with sugarml and this new shiny API to talk about code and concrete solutions in PR? Guess it will be easier for anyone.

**Comment by michael-ciniawsky** [comment]
https://sokra.github.io/source-map-visualization/

the example is js code but the source mappings (line: tag->col:[startOffset, endOffset], attrs->col:[startOffset, endOffset] content->col:[startOffeset, endOffset]) could be made for html (tag, attrs, content).

http://astexplorer.net/

parse5 with/without htmlparser2 tree adapter provides line, col, startOffset, endOffset information
For htmlparser2 which is more forgiving and faster there needs would likely be need to generate that info during PostHTML AST generation.

**Comment by michael-ciniawsky** [comment]
https://github.com/posthtml/posthtml-export 'monkey-patch' plugin approach to export HTML as a string wrapped in a function, but there is no way to use posthtml exp etc later. Only way is to the params of the template function later with es6 template literals.

**Comment by michael-ciniawsky** [comment]
```js
Node <Tag> {
  type: 'tag'
/*---------------------------*\
  space: '  '  get current indent/whitespace, use if new nodes are appended node.connte
               e.g node.content.push(`\n${node.space}`, {tag: 'section, attrs: {}, content: []}) ?
  tag: 'div'  
  attrs: {},
  content: [] || ''
\*---------------------------*/
  file: {
   path: ''
   name: ''
   ext: '' // not sure useful
   map: 'sourcemap string'
  }
}
```

```js
Node <Comment> {
  type: 'comment'
/*---------------------------*\
  space: '  ' 
  content: ''
\*---------------------------*/
  file: {
   path: ''
   name: ''
   ext: ''
   map: 'sourcemap string'
  }
}
```
this should be backwards compatibile, the AST will be enriched but the props for Node <Tag> don't change

**Comment by awinogradov** [comment]
Easy guys:) 

#### Error Reporting
We should build report system like in postcss. It would be plugin wich will collect errors and warnings from previous plugins. It is breaking changes for plugins. Because all plugins need to export name. But it's important for better development and we need do it ;) 

#### Source Maps
I absolutely agree with @zxqfox. @jescalan @michael-ciniawsky I don't know any reason to build source maps. Can you explain some examples from your real work where you need source maps? Sourcemaps was made for better debugging from browsers. They help you understand right places of your 'sugar' source and navigate you to the right position in the code. It works when we have file-based build system. Transformations in PostHTML can be totally destructive in general. We don't have files for concatenation and parse. String. Only God can know where it from and what plugins do with it ;) 

#### Code Generator > Function
@jescalan If I understand right you want better data changes for html. It's idea about template engines. Not every tool wich can generate string is a template engine :) PostHTML one of them. Of course, you can use it like template engine and add this functionality by plugins wich understand special notations for replacing. But any template engine will be faster ;) Because they don't have html parsing step. You need to understand this fact. Now PostHTML transforms html into the Object wich you can transform by JS functions. Matchers are functions what you want. When you write templates for template engine it is matchers too.

#### Dependency Tracking
@jescalan We need more information about this. Now I don't unersrtand what you mean. Example required ;)

Everybody should remember:) PostHTML returns string and PostHTML Tree. Not string only. You don't need parse string again you can use Tree. Also PostHTML can use Tree without parsing step.

It's my 50 cent ;)

**Comment by jescalan** [comment]
> But any template engine will be faster ;) Because they don't have html parsing step.

Not necessarily. Jade, for example, does parse the full source. A templating system like [ejs](http://ejs.co/) does not, and would absolutely be faster, but also does not offer the same functionality. EJS is *templating only*, with no possibility for any other type of transform, where posthtml allows a huge range of custom plugins and transforms, which, as we have seen, can be enormously useful. It's a tradeoff between speed and features. More speed, less power. More power, less speed. Fortunately, despite being quite powerful, posthtml is rather quick at the moment, and additionally will generate pre-rendered templates, so there will be no impact on performance in production.

> I don't know any reason to build source maps. Can you explain some examples from your real work where you need source maps?

I also have no desire to implement sourcemaps, as stated in my original issue. I don't use sourcemaps for any language, honestly, just not worth the effort for me. However, once this project becomes more popular, I guarantee that many people will ask for them. And although concerns have been expressed as to how they could be accurate and/or whether extra information would need to be added, they could easily be accurate, and no extra information would be needed on the AST other than line/col names, I promise. The ability to generate sourcemaps could even be added as a plugin outside of core.

This is at the very bottom of my priorities personally, I only bring it up because when this project starts getting publicity, you will start getting issue after issue with people asking for sourcemaps. It just happens, I think some people use tools where they edit from the browser, or are just very confused about where errors occur, or whatever. Since it doesn't seem like anyone in core is interested, I don't see any reason *we* should implement them, however we do need to have the resources in place for someone else who cares more to implement them in the future, so it needs to be taken into consideration.

> Dependency Tracking - Now I don't understand what you mean. Example required ;)

Let's say you are building a large static site. You are using a static build tool to do this, like gulp or webpack or something. You put it into "watch" mode in development, so that when one of your files changes, it will recompile and reload your browser. The build system

You are also using `posthtml-include` to include a partial in a couple of your pages. For example, a footer. It shows up on a bunch of pages, so you write it in one place and include it in others.

You make changes to the footer partial. Now the static build system has two options. It can see a change and recompile every single file in the site (which could take a very long time for large sites), or it can see a change and just recompile the single file that changed, which is a much better option.

However, if you changed the footer partial, you need to know what files use the footer partial so you can update them. Therefore, you need a *dependency tree* -- for each file, what other files does it depend on? Webpack for example has this built in by default. So when you use a webpack plugin, for each file you can return what other files are dependencies of that file. So your footer partial would have maybe your home and about pages as dependencies. Therefore when in watch mode and a change is detected to the footer partial, it would look at the dependencies and recompile those files.

If there is any plugin in posthtml that includes content (`posthtml-include` is the major use case, but surely there will be more), they need the ability to add dependencies. Luckily this is a small and simple change, but it makes things much easier for people working with larger sites that use posthtml.

> Guess you should take a quick look at bem-xjst project

I know that you guys over at theprotein.io are a big fan of this project, but we don't use it, nor do we use BEM at my company. Many people/companies do not use BEM, and would not be comfortable writing their html as JSON. That is the beauty of posthtml though -- you do not need to use some particular method of coding or structure in order to use it. You can use it with anything, and if the tool you want doesn't exist, you make it as a plugin.

For example, you could implement bem-xjst on top of posthtml using a custom parser and a plugin. The key is having posthtml as the foundation for any and all html processing, and layering plugins on top. There are a lot of advantages to this approach. Everyone can agree on the same base format. It's much easier to contribute as contributors don't need to jump in to a large project with custom parsers and their own conventions and rules and PRs, and can just write their own plugin and start using it immediately. And it comes with a large community of already-built plugins so that you can test things out and change between tools quickly without dropping a project entirely and switching to a new one when you want something different or new technologies emerge.

> are you willing to build a PoC with sugarml and this new shiny API to talk about code and concrete solutions in PR?

Would be happy to. Just wanted to collect some thoughts about the ideas and concept before moving forward, as this is quite a large change.

---

I know posthtml started out as a side project / experiment, but it has the potential to go really far. You have seen the rise of babel and postcss -- these are both projects built on exactly the same idea. We provide a parser and platform for plugins, you do the rest. Posthtml can and will be just as popular of an option. Are you guys ready?!

**Comment by awinogradov** [comment]
At first) You should understand one moment. If you want the tool for fun you don't need speed, right? But you want to use PostHTML in production, right? Speed is necessary for production :) I think you understand my idea. You don't need PostHTML like a base for the template engine. Projects with the same arch what you mean are tools for development. Not for production. If you want to prepare static html it can be ok, but it's strange. You have a plugin for this, I know. How can we help you in the core? 

Info) PostHTML Tree absolutely compatible with bem-xjst. bem-xjst doesn't use json like a html abstraction. JSON is the data for templates. Now we can translate tree between this technologies. And I want to save this feature in future;)

We have an [issue](https://github.com/posthtml/posthtml/issues/138) about source maps. We can continue the discussion there. If anybody wants to try to build them... And he knows how) So welcome) But we don't need this issue in the roadmap. No one feature doesn't depend on source maps.

You don't need to require resolver in PostHTML. It's work for the build system. You can use PostHTML with any. If you want extra files to watch you can write a pattern for the build system. It'll be incorrect if PostHTML looks on required packages. 

If you start to write the code it will be easy to understand. I'm sure. Really) Because we start to solve real problems from real life. Ideas are awesome, but code is better:) 

@jescalan I wouldn't want you to think that I'm looking for arguments against. But I really want arguments in order to do it. Just the desire is not always enough.

**Comment by jescalan** [comment]
> But you want to use PostHTML in production, right? Speed is necessary for production :)

Again, posthtml compiles into a string/function in development. This will make zero impact on production. If you use EJS, you get a function. If you use posthtml, you get a function. Posthtml with a bunch of plugins will be slower than ejs in development, but they will both generate the same result in production, so it makes no difference.

What does make a difference to speed up development work is dependency tracking, as mentioned in the previous comment, since it allows only the necessary changes in a project to be compiled.

> You don't need to require resolver in PostHTML. It's work for the build system. 

You definitely do. The build system cannot know what file dependencies a posthtml plugin adds to posthtml's AST. Only posthtml and the plugins can know this information. For this reason it's our responsibility.

We don't need to write the logic for only compiling when X changes, etc. We just need to give the build system a dependency tree, and it will do this rest. This is absolutely necessary, not really an optional feature, if posthtml is to be accepted as a stable framework to be used in production. Fortunately, it's not too difficult to implement.

> If you start to write the code it will be easy to understand. I'm sure. 

Sounds good. Let's wrap up this discussion, and I'll get some code going. Thanks to everyone for your feedback!

**Comment by awinogradov** [comment]
> Again, posthtml compiles into a string/function in development.
It's not right. html to object - right. But it's not necessary in this case. Can you explain changes in code? It'll be more productive to talk. It'll be better in separated issue.

> You definitely do. 
Definitely, no) All plugins and core can be required like a commonjs module. And all content in them to. If you pass this code to webpack you get all modules in a bundle. You can write ex when it doesn't work?

> I'll get some code going
Let's do it)
