### ISSUE TITLE
posthtml with posthtml-extend-attrs spoils templates

### ISSUE THREAD

**Issue by PaulMaly** [posthtml/posthtml#280]
I try to use `posthtml` with one of a component-based framework to extend some attributes in templates. So I've got this situation:

INPUT:

```html
<Layout foo={foo} {...props} />
```

OUTPUT:

```html
<Layout foo="{foo}" {...props}=""></Layout>
```

Unfortunately, these transformations break my templates. Can I somehow fix it?

**Comment by pmioni** [comment]
Same problem with AMP templates. Anyone can help? Is there an option to disable this "fixing" of attributes?

**Comment by PaulMaly** [comment]
Seems this project is inactive, unfortunately (((

**Comment by Scrum** [comment]
@pmioni @pmioni 

> Seems this project is inactive, unfortunately (((

Not quite reliably)

This problem is related [htmlparser2](https://github.com/fb55/htmlparser2) to with wrong parsing and the author is not particularly interested in solving this problem.

**Comment by chrisfwd** [comment]
I'm also having issues with this. I'm unable to add a disabled attribute to an element based on logic using posthtml templates. I am using rollup with rollup-plugin-posthtml-template but this issue seems to spawn from posthtml itself as I've tried other plugins with the same result. The only way I can accomplish adding the attribute 'disabled="disabled"' is by wrapping the whole HTML block in logic. That is not an ideal approach in my case because I would have two large blocks with the only difference being the attribute.

input: 
```<div ${_.disabled ? `disabled="disabled"` : ` `}>content</div>```

output: 
```<div {{_.disabled="" ?="" `disabled="disabled" `="" :="" `}}="">content</div>```

**Comment by Scrum** [comment]
`<div ${_.disabled ? `disabled="disabled"` : ` `}>content</div>` - this is not html syntax which makes it difficult to parse this piece

**Comment by Scrum** [comment]
Use the plugin [posthtml-boolean-attributes](https://github.com/posthtml/posthtml-boolean-attributes) to solve this problem
